name: Release

on:
  push:
    branches:
      - "master"

permissions:
  id-token: write  # Required for OIDC
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 22.x
          cache: "npm"
          scope: '@sitemark'

      # Ensure npm 11.5.1 or later is installed, so OIDC tokens work for
      # npm publishing
      - name: Update npm
        run: npm install -g npm@^11.5.1 && npm --version

      # We first have to remove package-lock because of https://github.com/npm/cli/issues/4828 ...
      - name: Install dependencies
        run: rm package-lock.json && npm install

      - name: Create Release Pull Request or Publish to github
        uses: changesets/action@v2
        with:
          # This also does a build
          publish-script: npm run release
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          HOME: ${{ github.workspace }}
